export { FormBarcodeComponent } from "./form-barcode.component"
export { FormCheckComponent } from "./form-check.component"
export { FormDateComponent } from "./form-date.component"
export { FormNumberComponent } from "./form-number.component"
export { FormSelectComponent } from "./form-select.component"
export { FormRecordComponent } from "./form-record.component"
export { FormTextComponent } from "./form-text.component"
